# .readthedocs.yaml

# Required version of Read the Docs configuration
version: 2

# Sphinx configuration
sphinx:
  configuration: source/conf.py

# Python configuration
python:
  version: 3.8  # Adjust to your Python version if necessary
  install:
    - requirements: source/requirements.txt  # Path to your requirements file

# Optional: specify output formats if you want PDFs, ePubs, etc.
formats:
  - pdf
  - epub
