# .readthedocs.yaml

# Required version of Read the Docs configuration
version: 2

# Sphinx configuration
sphinx:
  configuration: source/conf.py  # Adjust this path based on the location of conf.py

# Python configuration
python:
  version: 3.8  # or another compatible Python version
  install:
    - requirements: source/requirements.txt  # Path to dependencies if needed

# Optional: specify output formats if you want PDFs, ePubs, etc.
formats:
  - pdf
  - epub
